config/routes.rb
Rails.application.routes.draw do
   match '/home', to: 'homepage#index', via: 'get'
   match '/pc', to: 'homepage#downloadpc', via: 'get'
   root 'homepage#index'

   #resources :scores
   match '/score', to: 'highscores#index', via: 'get'
end

app/models/score.rb
class Score < ActiveRecord::Base
  scope :top, -> { order(score: :desc).limit(24) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/highscores_controller.rb
class HighscoresController < ApplicationController
 
  def index
    if params[:score].nil? != true then
      if params[:player].length >= 3 and params[:score] != "0" then
        cleanedparams = {:score => params[:score].to_i, :player => params[:player] }
        @score = Score.new(cleanedparams)
        @score.save
      end
    end
    @showscores = Score.top
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
  
  def downloadpc
    #send_file 'app/product/xrobotsattack.zip', filename: 'xrobotsattack.zip',
     #  type: 'application/zip',
       
    send_file 'app/product/xrobots.exe', filename: 'xrobots.exe',
       type: 'application',
       disposition: 'attachment'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/highscores/index.html.erb
<file splitter>
<% @showscores.each do |s| %>
~<%= s.score %>,<%= s.player %>~
<% end %>
<file splitter>

app/views/homepage/index.html.erb
<div class="center hero-unit" bgcolor="black">

<div align="center">
  <div class="well well-sm" style="width: 390px" color="black">
  	<%= image_tag("background.png") %>
    <h5 color = 'white'>Destroy the X Robots by making them crash into each other or crash into a pile of radioactive debris</h5>
    <%= link_to "Download for Windows", pc_path, class: "btn btn-large btn-primary" %>

    <h3>Movement</h3>
    <div align="left">
    <h5>The "O" character has letters around it indicating
    <br>which direction you can move.
    <br>After you move one space,
    <br>every X Robot will move towards you.
    <br>Watch them DIE when they touch the radioactive debris (the red # characters)
    </h5></div>
    
    <h3>Teleportation</h3>
    <div align="left">
    <h5>Type a 'T' and you will be placed someplace new.
    <br>That might kill you.
    </h5></div>
    
    <h3>The Ultimate Screwdriver</h3>
    <div align="left">
    <h5>If an X Robot is next to you, the screwdriver
    	<br>will short their power source and they die.
    <br>The screw driver will turn up to 8 X robots into rubble
    <br>if you are sorrounded
    <br>The screwdriver works only once per screen, 
    <br>choose wisely!
    </h5></div>
  </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xrobotsattack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>